site_name: conocimiento-en-bits
site_url: https://conocimiento-en-bits.neocities.org/
theme:
  name: 'material'
  palette: 
    - scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate 
      primary: pink
      accent: pink
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
    - Home: index.md
    - 2º ASIR3:
        - 'ej1-pull-request': '2021-09-22-ej1-pull-request.md'
        - 'app-web-estatica': '2021-10-5-implantacion-despliegue-aplicacion-web-estatica.md'
        - 'ej2-pr-pag-compañero': '2021-10-14-ej2-pr-pag-compañero.md'
        - SRI:
            - 'ej1-playbook-sencillo': '2021-09-22-ej1-playbook-sencillo.md'
            - 'ej2-router-nat-vagrant': '2021-10-1-ej2-router-nat-vagrant.md'
            - 'ej3-config-escenario-router-nat': '2021-10-3-ej3-config-escenario-router-nat.md'
            - 'Ej1 DHCP': 'ej1-instalar-configurar-dhcp.md'
            - 'Ej2 reserva DHCP': 'ej2-reserva-dhcp.md'
            - 'Práctica DHCP': 'practica-servidor-dhcp.md'
            - 'Ejercicio 1 Mapeo de URLs': 'ej1-mapeo-urls-al-sistema-ficheros.md'
    - About: about.md
extra:
  disqus: conocimiento-en-bits-neocities-org
