site_name: conocimiento-en-bits
theme:
  name: 'material'
  features:
    - content.code.annotate
    - navigation.tabs
  icon:
    logo: material/linux
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
nav:
    - Principal: index.md
    - 2º ASIR 21/22:
        - SRI:
            - Vagrant y Ansible:
                - 'Ejercicio 1: Playbook sencillo': 'ej1-playbook-sencillo.md'
                - 'Ejercicio 2: router NAT vagrant': 'ej2-router-nat-vagrant.md'
                - 'Ejercicio 3: Configuración escenario router NAT': 'ej3-config-escenario-router-nat.md'
            - DHCP:
                - 'Ejercicio 1': 'ej1-instalar-configurar-dhcp.md'
                - 'Ejercicio 2: reservas': 'ej2-reserva-dhcp.md'
                - 'Práctica': 'practica-servidor-dhcp.md'
            - HTTP:
                - 'Ejercicio 1: Mapeo de URLs': 'ej1-mapeo-urls-al-sistema-ficheros.md'
                - 'Ejercicio 2: Control de acceso': 'ej2-control-acceso-autenticacion-autorizacion.md'
                - 'Ejercicio 3: .htaccess con Apache': 'ej3-apache-.htaccess.md'
                - 'Ejercicio 4: Módulos en Apache': 'ej4-modulos-apache.md'
                - 'Ejercicio 5: VPS': 'ej5-vps.md'
                - 'Ejercicio 6: Apache proxy inverso': 'ej6-apache-proxy-inverso.md'
                - 'Práctica: LEMP en VPS': 'practica3-LEMP-VPS.md'
            - DNS:
                - 'Ejercicio 1: bind9': 'ej1-instalar-configurar-bind9.md'
                - 'Ejercicio 2: Slave DNS': 'ej2-instalar-configurar-slave.md'
                - 'Ejercicio 3: Delegación subdominios': 'ej3-delegacion-subdominio-bind9.md'
                - 'Práctica: DNS+Web+BD en escenario': 'practica-web-bd-dns-escenario.md'
            - HTTPS (1ª Parte):
                - 'Práctica: HTTPS en VPS': 'practica-https-vps.md'
            - HTTP (2ª Parte):
                - 'Práctica: Aumento rendimiento web': 'practica-aumento-rendimiento-web.md'
            - Correo:
                - 'Ejercicios en escenario libvirt': 'ejercicios-correo.md'
                - 'Práctica: Servidor de correos en VPS': 'practica-servidor-correo.md'
            - HA Clusters:
                - 'Práctica': 'practica-cluster-ha.md'
        - IAW:
            - 'ej1-pull-request': '2021-09-22-ej1-pull-request.md'
            - 'app-web-estatica': '2021-10-5-implantacion-despliegue-aplicacion-web-estatica.md'
            - 'ej2-pr-pag-compañero': '2021-10-14-ej2-pr-pag-compañero.md'
            - PHP:
                - 'Ejercicio 1: phpMyAdmin': 'ej1-phpmyadmin.md'
                - 'Ejercicio 2: BookMedik': 'ej2-bookmedik.md'
                - 'Ejercicio 3: php-fpm': 'ej3-phpfpm.md'
                - 'Práctica 1: Apps PHP': 'practica1-implantacion-apps-php.md'
                - 'Práctica 2: Instalación/migración de apps a VPS': 'practica2-instalacion-migracion-apps-PHP-en-VPS.md'
            - Python:
                - 'Ejercicio 1: Apache + mod_wsgi': 'ej1-apps-flask-apache2-mod_wsgi.md'
                - 'Ejercicio 2: Apache/Nginx + Gunicorn': 'ej2-apache2-gunicorn.md'
                - 'Ejercicio 3: Apache/Nginx + uWSGI': 'ej3-apache-uwsgi.md'
                - 'Práctica: Despliegue python': 'practica-despliegue-apps-python.md'
                - 'Práctica: CMS Python': 'practica-cms-python.md'
            - Java:
                - 'Práctica: CMS Java': 'practica-cms-java.md'
            - Docker:
                - 'Ejercicios': 'ejs-docker.md'
                - 'Práctica: BookMedik en Docker': 'practica-docker-php.md'
                - 'Práctica: Django tutorial en Docker': 'practica-docker-python.md'
        - SAD:
            - 'Criptografía 1: Cifrado asímetrico': 'practica-cifrado-asimetrico-gpg-openssl.md'
            - 'Criptografía 2: Firmas': 'practica-integridad-firmas-autenticacion.md'
            - 'Práctica: VPN': 'practica-vpn-sad.md'
            - Cortafuegos:
                - 'Ejercicio 1 iptables: por nodo': 'ej1-iptables-nodo.md'
                - 'Ejercicio 1 nftables: por nodo': 'ej1-nftables-nodo.md'
                - 'Ejercicio 2 iptables: perimetral': 'ej2-iptables-perimetral.md'
                - 'Ejercicio 2 nftables: perimetral': 'ej2-nftables-perimetral.md'
                - 'Práctica iptables: perimetral escenario': 'perimetral-iptables-escenario.md'
        - 'Escenario libvirt': 'practica-escenario-libvirt.md'
    - 2º ASIR 22/23:
        - ASO:
            - 'Instalación Debian 11': 'aso/instalacion_debian11.md'
            - 'Instalación Debian 11 preseed': 'aso/debian11_automatico.md'
            - 'Ejercicios de paquetería': 'aso/ejercicios-paqueteria.md'
            - Kernel:
                - 'Teoría': 'aso/teoria-kernel.md'
                - 'Ejercicios de módulos': 'aso/ejercicios-de-modulos.md'
                - 'Ejercicios de parámetros': 'aso/ejercicios-parametros-kernel.md'
                - 'Compilación programas C': 'aso/compilacion-programas-c.md'
                - 'Compilación de Kernel': 'aso/compilacion-kernel.md'
            - Red Hat:
                - 'Migración CentOS': 'aso/migracion-centos.md'
        - BD:
            - 'Prueba inicial': 'bd/prueba-inicial.md'
            - 'Práctica 1': 'bd/p1-servidores-clientes.md'
            - 'Práctica 2': 'bd/p2-interconexion-bd.md'
            - 'Examen prácticas 1 y 2': 'bd/examen-practicas-1-2.md'
        - HLC:
            - Virtualización en Linux:
                - 'Taller 1': 'hlc/taller1-virtualizacion.md'
                - 'Taller 2': 'hlc/taller2-virtualizacion.md'
                - 'Taller 3': 'hlc/taller3-virtualizacion.md'
                - 'Taller 4': 'hlc/taller4-virtualizacion.md'
                - 'Taller 5': 'hlc/taller5-virtualizacion.md'
                - 'Taller 6': 'hlc/taller6-virtualizacion.md'
                - 'Práctica': 'hlc/practica-virtualizacion.md'
            - OpenStack:
                - 'Taller 1': 'hlc/taller1-cliente-vpn.md'
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
extra_css:
  - stylesheets/asciinema-player.css
extra_javascript:
  - javascripts/asciinema-player.min.js
plugins:
  - glightbox
  - search
  - mkdocs-asciinema